name: Feature Request
description: no we aint adding extra keys or winning icons to the engine, theres scripts that do those things that you can steal, pls stop asking for that
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested. (pick the wrong option and you get an f on your test)
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - 6K+ support and winning icons.
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
